# Generated by Django 4.2 on 2023-05-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_kraskah', '0002_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='img',
            field=models.ImageField(help_text='150x150px', null=True, upload_to='media/images', verbose_name='ссылка картинки'),
        ),
    ]
