# Generated by Django 4.2 on 2023-05-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_kraskah', '0003_teacher_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите возрастную группу', max_length=200, verbose_name='Возрастная группа')),
            ],
            options={
                'verbose_name': 'Возраст',
                'verbose_name_plural': 'Возраста',
                'ordering': ['name'],
            },
        ),
    ]
