# Generated by Django 4.2 on 2023-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_kraskah', '0004_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age_group',
            field=models.ManyToManyField(help_text='Введите группу преподавания', to='v_kraskah.groups', verbose_name='группа преподавания'),
        ),
    ]
