# Generated by Django 4.1.5 on 2023-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_kraskah', '0006_category_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='media/images', verbose_name='ссылка картинки'),
        ),
    ]
