# Generated by Django 4.1.5 on 2023-05-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_kraskah', '0007_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_description',
            field=models.CharField(blank=True, help_text='Полный текст курса', max_length=1000, verbose_name='полное описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='media/images/category', verbose_name='ссылка картинки'),
        ),
    ]
