# Generated by Django 4.1.5 on 2023-05-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_kraskah', '0010_groups_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='ages',
            field=models.CharField(blank=True, help_text='Введите возрастную группу', max_length=200, verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(help_text='Введите название возрастной группы', max_length=200, verbose_name='Название возрастной группы'),
        ),
    ]
