# Generated by Django 4.1.5 on 2023-05-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_kraskah', '0011_groups_ages_alter_groups_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
