# Generated by Django 4.1.5 on 2023-05-14 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_kraskah', '0012_rename_groups_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=100, verbose_name='Имя клиента')),
                ('phoneNumber', models.CharField(help_text='Номер телефона', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона клиента')),
            ],
        ),
    ]
