# Generated by Django 4.1.5 on 2023-05-14 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_kraskah', '0014_alter_usercallback_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercallback',
            name='phoneNumber',
            field=models.CharField(help_text='Номер телефона', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона клиента'),
        ),
    ]
